# Generated by Django for: add mobile_number field to User model

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=20, blank=True, null=True, unique=True, help_text="User's mobile phone number."),
        ),
    ]
